// Generated by CoffeeScript 1.7.1
var footer, tongji;

tongji = '';

footer = "<link rel='stylesheet' type='text/css' href='ui/css/footer.css' /><div class='step2_foot'><div class='step2_foot_area'><div class='step2_foot_area_left'>工作时间：09：00 - 18：00</div><div class='step2_foot_area_right'>月木视觉 | Copyrights MOONVISION. ALL Rights Reserved</div></div>" + tongji + "</div>";

document.write(footer);
