// Generated by CoffeeScript 1.7.1
var bindBookItem, enterLastStep, enterNext, getNowDate, initItem, selectFrameClick, showStep, _displayCalendar;

$("body").css("background-color", "#86cbc8");

selectFrameClick = function() {
  $(this).find('.select-frame').toggleClass('select-frame-selected');
};

getNowDate = function() {
  var D, M, current, fullY;
  current = new Date();
  fullY = current.getFullYear();
  M = current.getMonth() + 1;
  D = current.getDate();
  return fullY + "-" + M + "-" + D;
};

initItem = function() {
  var item, select_date, step;
  step = GetCookie('step') || '1';
  item = GetCookie('item') || 'wedding';
  select_date = GetCookie('select_date');
  showStep(step, item, select_date);
};

showStep = function(step, item, date, infoObj) {
  SetCookie('step', step, 3600);
  SetCookie('item', item, 3600);
  if (+step === 1 || item === 'kids') {
    if (date) {
      SetCookie('select_date', date, 3600);
      $('#selectedDate').text(date);
    }
    if (infoObj) {
      console.log(infoObj);
    }
    $('.book-term-content-container-padding').hide();
    $("." + item).show();
    _displayCalendar(date);
    $('.step').hide();
    $("#step" + step).show();
  } else if (+step === 1 || (item === 'wedding' || item === 'marry')) {
    removeCookie('step');
    $('.step').hide();
    $("#steperror").show();
  } else {
    removeCookie('step');
    $('.step').hide();
    $("#steperror").show();
  }
};

_displayCalendar = function(date) {
  var dateDuration, daysInMonth, first_date, html, i, j, last_date, weekDay, weekHtml, _currDate, _i, _j, _month, _ref, _ref1;
  first_date = new Date();
  if (date) {
    first_date = new Date(date);
  }
  last_date = first_date.clone().addMonths(5);
  dateDuration = first_date.format('{yyyy}.{M}') + ' — ' + last_date.format('{yyyy}.{M}');
  $('#book-select-date-text').html(dateDuration);
  html = '';
  weekHtml = '<tr><th>日</th><th>一</th><th>二</th><th>三</th><th>四</th><th>五</th><th>六</th></tr>';
  for (i = _i = 1; _i <= 6; i = ++_i) {
    _currDate = first_date.clone().addMonths(i - 1);
    _month = _currDate.getMonth() + 1;
    html += '<li><p>' + _month + '月</p><div class="book-select-date-item-content-container"><table style="width:100%">' + weekHtml + '<tr>';
    daysInMonth = _currDate.daysInMonth();
    weekDay = new Date(_currDate.getFullYear() + '-' + (_currDate.getMonth() + 1) + '-1').getDay();
    for (j = _j = _ref = 1 - weekDay, _ref1 = daysInMonth; _ref <= _ref1 ? _j <= _ref1 : _j >= _ref1; j = _ref <= _ref1 ? ++_j : --_j) {
      if (j > 0) {
        html += '<td><a class="book-select-date-item" data-date="' + _currDate.format('{yyyy}-{M}-' + j) + '">' + j + '</a></td>';
      } else {
        html += '<td></td>';
      }
      if (j > 0 && (j + weekDay) % 7 === 0) {
        html += '</tr><tr>';
      }
    }
    html += '</tr></table></div></li>';
  }
  $('#displayCalenderContainer').html(html);
  return $('#step3 .book-select-date-item').on('click', {
    step: 4
  }, enterNext);
};

enterNext = function(d) {
  var item, step;
  step = +d.data.step;
  item = $(this).data('item') || GetCookie('item') || 'wedding';
  showStep(step, item, $(this).data('date'));
};

enterLastStep = function(d) {
  var cookies;
  enterNext(d);
  cookies = ['item', 'select_date'];
  removeCookies(cookies);
};

bindBookItem = function() {
  initItem();
  $('.label-radio').on('click', selectFrameClick);
  $('#step1 .book-items a').on('click', {
    step: 2
  }, enterNext);
  $('#step2 #book-term-agree').on('click', {
    step: 3
  }, enterNext);
  $('#step2 #book-term-reject').on('click', {
    step: 1
  }, enterNext);
  $('#step3 #book-select-date-back-a').on('click', {
    step: 2
  }, enterNext);
  $('#step3 #step3_return').on('click', {
    step: 2
  }, enterNext);
  $('#step4 #reSelectDate').on('click', {
    step: 3
  }, enterNext);
  $('#step4 #book-detail-info-submit').on('click', {
    step: 5
  }, enterNext);
  $('#step4 #book-detail-info-cancel').on('click', {
    step: 3
  }, enterNext);
  $('#step5 #book-confirm-agree').on('click', {
    step: 6
  }, enterLastStep);
  $('#step5 #book-confirm-reject').on('click', {
    step: 4
  }, enterNext);
  $('#steperror a#steperror_return').on('click', {
    step: 1
  }, enterNext);
};

bindBookItem();
