// Generated by CoffeeScript 1.7.1
var enums;

enums = (function() {
  return {
    packageName: {
      1: 'MOONKIDS套餐1',
      2: 'MOONKIDS套餐2'
    },
    bookingTime: {
      1: '上午9：30',
      2: '下午2：00'
    }
  };
})();
