// Generated by CoffeeScript 1.7.1
var enums;

enums = (function() {
  return {
    packageName: {
      1: 'MOONKIDS套餐1',
      2: 'MOONKIDS套餐2'
    },
    bookingTime: {
      1: '上午 9：30',
      2: '下午 2：00'
    },
    orderStatus: {
      0: '未支付定金',
      1: '支付完成，等待拍摄',
      2: '拍摄完成'
    },
    orderStatusBtnText: {
      0: '继续付款',
      1: '我还要预订',
      2: '我还要预订'
    },
    address: '上海市杨浦区大学路292号702'
  };
})();
