// Generated by CoffeeScript 1.7.1
var loginClick, _check, _initCaptcha;

$("body").css("background-color", "#86cbc8");

_check = '';

_initCaptcha = function(scale) {
  var i, _i, _index, _pool;
  _check = '';
  scale = scale || 4;
  _pool = ['1', '2', '3', '4', '5', '6', '7', '8', '9'];
  for (i = _i = 0; 0 <= scale ? _i < scale : _i > scale; i = 0 <= scale ? ++_i : --_i) {
    _index = 0;
    _index = parseInt(Math.random() * 9);
    _check += _pool[_index];
  }
  $('#captcha-checkcode').text(_check);
};

loginClick = function() {
  var obj, postData, txtCaptcha, txtPwd, txtTel;
  txtTel = $('#txtTel').val();
  txtPwd = $('#txtPwd').val();
  txtCaptcha = $('#txtCaptcha').val();
  postData = {
    tel: txtTel,
    pwd: txtPwd,
    captcha: txtCaptcha
  };
  if (txtCaptcha !== _check) {
    $('#err-info').text('验证码不正确');
    _initCaptcha(4);
    return;
  }
  obj = {
    contentType: 'application/x-www-form-urlencoded;charset=utf-8',
    bc: function(rs) {
      var cookies;
      if (rs.id && rs.username) {
        cookies = ['item', 'select_date', 'step'];
        removeCookies(cookies);
        SetCookie('account', rs.username, 3600);
        SetCookie('accountid', rs.id, 3600);
        location.href = "booking.html";
      } else {
        $('#err-info').text('手机号码或密码错误');
        $('#txtTel').val('');
        $('#txtPwd').val('');
        $('#txtCaptcha').val('');
        _initCaptcha(4);
      }
    }
  };
  ajax('POST', '/CGI-BIN/login.pl', postData, obj);
};

_initCaptcha(4);

$('#btn-login').on('click', loginClick);

$('#captcha-checkcode').on('click', function() {
  _initCaptcha(4);
});
