// Generated by CoffeeScript 1.7.1
var modal;

modal = function(type, modalId, title, content, ok, init) {
  var _showAlertModal, _showConfirmModal, _showInfoModal, _showPopModal;
  _showAlertModal = function(title, content) {
    var modalObj;
    modalObj = $('#alertModal');
    modalObj.find('.modalLabel').html(title);
    modalObj.find('.modal-body-content').html(content);
    modalObj.modal('show');
  };
  _showConfirmModal = function(title, content, ok) {
    var modalObj;
    modalObj = $('#confirmModal');
    modalObj.find('.modalLabel').html(title);
    modalObj.find('.modal-body-content').html(content);
    modalObj.find('.btn-ok').off('click').on('click', function() {
      ok();
      return modalObj.modal('hide');
    });
    modalObj.modal('show');
  };
  _showInfoModal = function(modalId, title, content) {
    var modalObj;
    modalId = modalId || 'infoModal';
    modalObj = $("#" + modalId);
    modalObj.find('.modalLabel').text(title);
    modalObj.find('.modal-body-content').html(content);
    modalObj.modal('show');
  };
  _showPopModal = function(modalId, title, ok, initFn) {
    var modalObj;
    modalId = modalId || 'popModal';
    modalObj = $("#" + modalId);
    modalObj.find('.modalLabel').text(title);
    modalObj.find('.btn-ok').off('click').on('click', function() {
      ok();
      if (!initFn.notAutoClose) {
        return modalObj.modal('hide');
      }
    });
    if (initFn.fn_show) {
      modalObj.off('show.bs.modal').on('show.bs.modal', initFn.fn_show);
    }
    if (initFn.fn_shown) {
      modalObj.off('shown.bs.modal').on('shown.bs.modal', initFn.fn_shown);
    }
    if (initFn.fn_hide) {
      modalObj.off('hide.bs.modal').on('hide.bs.modal', initFn.fn_hide);
    }
    if (initFn.fn_hidden) {
      modalObj.off('hidden.bs.modal').on('hidden.bs.modal', initFn.fn_hidden);
    }
    if (initFn.ok_text) {
      modalObj.find('.btn-ok').text(initFn.ok_text);
    }
    if (initFn.close_text) {
      modalObj.find('.btn-close').text(initFn.close_text);
    }
    modalObj.modal('show');
  };
  switch (type) {
    case 'confirm':
      _showConfirmModal(title, content, ok);
      break;
    case 'alert':
      _showAlertModal(title, content);
      break;
    case 'pop':
      _showPopModal(modalId, title, ok, init);
      break;
    case 'info':
      _showInfoModal(modalId, title, content);
  }
};
