use CGI;
use DBI;
my $cgi = CGI->new;
my $book_time = $cgi->param("book_time");
my $book_am_pm = $cgi->param("book_am_pm");
my $order_id = $cgi->param("order_id");
my $account_id = $cgi->param("account_id");
my $detail = $cgi->param("detail");
my $dbh = DBI->connect("DBI:mysql:database=hdm174585245_db;host=hdm174585245.my3w.com;port=3306",  
  "hdm174585245", "hmw223410") or die $DBI::errstr;
print "Content-type: text/plain\n\n";
my $statement = qq{insert into booking (book_time, book_am_pm, order_id, account_id, detail) values (?,?,?,?,?)};
my $sth = $dbh->prepare($statement) or die $dbh->errstr;
$book_time = "$book_time";
$book_am_pm = $book_am_pm;
$order_id = "$order_id";
$account_id = $account_id;
$detail = "$detail";
$sth->execute($book_time, $book_am_pm, $order_id, $account_id, $detail) or die $sth->errstr;
# print $sth->rows;
print "1";
$sth->finish();
$dbh->disconnect;